### ISSUE TITLE
Error While Trying to Update Houseing Borders in Time Lapse Mode for Housing unlocked while in Time Lapse

### ISSUE THREAD

**Issue by KeinNiemand** [Psycho-Ray/AutoTrimps#27]
When AT tries to update the border color of housing in Time Lapse/Catching up to Lost Time mode, it fails and I repidetly get this error in the console

buildings.js:81 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at buildings.js:81:60
    at Array.forEach (<anonymous>)
    at buyFoodEfficientHousing (buildings.js:81:21)
    at buyBuildings (buildings.js:195:9)
    at mainLoop (AutoTrimps2.js:199:13)
    
What's probably happening is that the GUI elements it's trying to update don't exist while in time lapse mode, so some kind of check needs to be added so AT dosn't try to update borders while in time lapse. The same problem may or may not happen for equipment or any other borders it tries to update.

I've reported the same problem on Zeks version, since both forks have this bug.

**Comment by KeinNiemand** [comment]
After some further testing and debugging this error I've found out that this error only happens when a new housing is unlocked while time time lapse/offline mode. While the GUI elements for housing that's already unlocked is already loaded, the UI elements for Newley unlocked housing are undefined if they have been unlocked while in time lapse. This may or may not also be the case for equipment/upgrades/other stuff.
